### ISSUE TITLE
Ability to check battery level

### ISSUE THREAD

**Issue by mchapman2** [owntracks/electron#1]
It would be nice to have the ability to monitor battery level. Can this be included?

**Comment by jpmens** [comment]
It's unlikely that this is possible without some adding a bunch of electronics (which we just cannot; cannot as in _are not capable of_). The Electron will be powered by 5V (e.g. USB) and has no knowledge of battery level...

**Comment by jpmens** [comment]
Looking around a bit, it _may_ be that something like this [SparkFun LiPo Fuel Gauge](https://www.sparkfun.com/products/10617) would do the trick (pasted here for posterity):

> The SparkFun LiPo Fuel Gauge connects your battery to your project and uses a sophisticated algorithm to detect relative state of charge and direct A/D measurement of battery voltage. In other words, it tells your microcontroller how much ‘fuel’ is left in the tank. The LiPo Fuel Gauge communicates with your project over I2C and an alert pin also tells you when the charge has dropped below a certain percentage.

I have no experience with these.

**Comment by mchapman2** [comment]
Ok...it was a thought.

Thanks,

Mike

**Comment by ckrey** [comment]
> You'll also be able to monitor battery levels using the Photon itself,
https://store.particle.io/?utm_source=Homesite&utm_medium=Button&utm_content=Proto&utm_campaign=buydevkit

and in the "POWERSHIELD" library:
```
    // Read the volatge of the LiPo
    float cellVoltage = batteryMonitor.getVCell();
    // Read the State of Charge of the LiPo
    float stateOfCharge = batteryMonitor.getSoC();
```

**Comment by jpmens** [comment]
Indeed, you're right @ckrey, but that shield adds another $25 to the device ...

**Comment by mchapman2** [comment]
Thanks for the info Christoph

**Comment by mchapman2** [comment]
What about adding an accelerometer? It could be used to detect tampering.

Mike

**Comment by jpmens** [comment]
Battery level will be reported by the Electron.
